In [2]:
import numpy as np
import math as m

In [2]:
28*28

784

In [4]:
m.ceil(13/4)

4

In [7]:
A = np.array([[1, -2], [0, 3]])
A = np.maximum(A, 0)

In [8]:
A

array([[1, 0],
       [0, 3]])

In [14]:
dLdA = np.array([[0.234, -3.15],[2, 0.5]])
dLdA

array([[ 0.234, -3.15 ],
       [ 2.   ,  0.5  ]])

In [10]:
A!=0

array([[ True, False],
       [False,  True]])

In [13]:
dLdA * (A!=0)

array([[ 0.234, -0.   ],
       [ 0.   ,  0.5  ]])